# Generated by Django 3.1.3 on 2022-07-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_title', models.CharField(max_length=50)),
                ('map_sheet_number', models.IntegerField()),
            ],
        ),
    ]
